Level18_1 Bages
Nikolaytk87/test-guru pull request #17
Opened 2022-12-04 17:40 UTC by Nikolaytk87

Bages

2022-12-05 04:07 UTC, VidgarVii requested changes

2022-12-05 04:07 UTC, VidgarVii commented on app/services/badge_reward_service.rb
> +  def category?(category)
не верен что для сервиса все методы ниже стоит делать публичными. Внутреннюю реализацию объекта всегда надо скрывать

2022-12-05 04:07 UTC, VidgarVii commented on app/services/badge_reward_service.rb
> +    return if @test.category.title != category
такие проверки лучше делать по "ай-ди" (в большинстве случаев)
обрати внимание - в модели Категори нет проверки "тайтл" на уникальность, т.е. по "ай-ди" будет явно надежней
да и проще будет в данном случае - не надо будет подгружать объект `category`
```ruby
... if @test.category_id != category_id
```

2022-12-05 04:07 UTC, VidgarVii commented on app/services/badge_reward_service.rb
> +  end
надо учесть тот момент что кол-во баджев (правил) будет только увеличиваться. Это приведёт к раздутию данного файла. А вот то что кол-во файлов увеличиться это не страшно. По этому лучше всего абстрагировать код для правил отдельно в классы. 
От этого так же получим больше пользы, так как распределим обязанности по классам. Данный сервис будет отвечать за выдачу баджа, а за правила пусть отвечают другие объекты. Т.е. нужен объект у которого можно спросить выдавать бадж или нет .
Для правил отлично подходит паттерн Спецификация.(Если у тебя получиться его разобрать это будет просто супер решением)

2022-12-05 14:05 UTC, Nikolaytk87 commented on app/services/badge_reward_service.rb
> +    return if @test.category.title != category
Не совсем понял
category, это опция, которая передается строкой, она сравнивается с названием категории теста, которую прошел пользователь и если не совпадает, то выходим из функции. 
`if @test.category_id != category_id` - это работать не будет

2022-12-06 03:51 UTC, VidgarVii commented on app/services/badge_reward_service.rb
> +    return if @test.category.title != category
еще раз.
сравнение по тайтлу категории это не надёжный и излишний способ.
1 title может быть не уникален
2 title можно изменить добавив для него контроллер с CRUD
3 title не храниться в тесте и это пораждает лишние запросы в базу.
4 title не идентифицирует объект. За это отвечает только поле ID

2022-12-06 10:01 UTC, merged