Lesson 3
Nikolaytk87/test-guru pull request #2
Opened 2022-11-04 11:19 UTC by Nikolaytk87

Decision to 3 lectures

2022-11-04 12:59 UTC, VidgarVii requested changes

2022-11-04 12:59 UTC, VidgarVii commented on db/migrate/20221103160831_create_tests.rb
> +    add_reference :tests, :category
связи нужны. Но это можно и лучше сделать сразу при создании таблицы

t.references :category, null: false, foreign_key: true

2022-11-04 12:59 UTC, VidgarVii commented on db/migrate/20221103160831_create_tests.rb
> +      t.integer :level, default: 0
null: false
нам ведь не нужны пустые значения
default не гарантирует, что не будет null

2022-11-04 12:59 UTC, VidgarVii commented on db/migrate/20221103160831_create_tests.rb
> +    add_reference :tests, :category
для теста нам еще понадобиться автор. Это юзер который создал тест. Но при этом по названию колонки должно быть понятно, что речь идёт именно об авторе теста. Предлагаю это сделать в текущем ПР.

2022-11-04 12:59 UTC, VidgarVii commented on db/migrate/20221104111050_create_answers.rb
> +      t.boolean :correct, default: false
для логических полей рекомендуется указывать опцию `null: false`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2022-11-05 08:26 UTC, VidgarVii requested changes

2022-11-05 08:26 UTC, VidgarVii commented on db/migrate/20221103160831_create_tests.rb
> +      t.references :test_author, null: false, foreign_key: true
test_author
c таким названием запрос получится таким
test.test_author
тавталогия получается. лучше просто атрибут назвать author

2022-11-05 08:26 UTC, VidgarVii commented on db/migrate/20221103160831_create_tests.rb
> +      t.references :test_author, null: false, foreign_key: true
второй момент, такой ключ не будет работать. Так как Внешний ключ отвечает за ссылочную целостность данных. А сейчас ключ будет смотреть в таблицу test_authors. А её нет... По этому надо ключу указать, что смотреть надо на таблицу юзеров foreign_key: { to_table: :questions })

2022-11-05 08:26 UTC, VidgarVii commented on db/migrate/20221104111050_create_answers.rb
> +      t.references :test, null: false, foreign_key: true
ответ принадлежит вопросу, а не тесу

2022-11-05 10:07 UTC, Nikolaytk87 commented on db/migrate/20221103160831_create_tests.rb
> +      t.references :test_author, null: false, foreign_key: true
Поправил

2022-11-05 10:08 UTC, Nikolaytk87 commented on db/migrate/20221104111050_create_answers.rb
> +      t.references :test, null: false, foreign_key: true
Поправил

2022-11-06 12:07 UTC, merged